import turtle


screen = turtle.Screen()
screen.screensize(800,800)
screen.bgcolor('snow')

t_ground = turtle.Turtle()
t_ground.hideturtle()
t_ground.penup()
t_ground.speed(0)

t_ground.fillcolor('snow1')
t_ground.goto(-1000,-100)
t_ground.begin_fill()
t_ground.goto(1000,-100)
t_ground.goto(1000,-1000)
t_ground.goto(-1000,-1000)
t_ground.goto(-1000,-100)
t_ground.end_fill()

t_ground.fillcolor('light gray')
t_ground.begin_fill()
t_ground.penup()
t_ground.goto(-30,65)
t_ground.pendown()
t_ground.circle(20)
t_ground.end_fill()

t_ground.fillcolor('black')
t_ground.begin_fill()
t_ground.penup()
t_ground.goto(-38,88)
t_ground.pendown()
t_ground.circle(5)
t_ground.end_fill()

t_ground.fillcolor('black')
t_ground.begin_fill()
t_ground.penup()
t_ground.goto(-22,88)
t_ground.pendown()
t_ground.circle(5)
t_ground.end_fill()

t_ground.fillcolor('orange')
t_ground.begin_fill()
t_ground.penup()
t_ground.goto(-30,77)
t_ground.pendown()
t_ground.circle(5)
t_ground.end_fill()

t_ground.fillcolor('light gray')
t_ground.begin_fill()
t_ground.penup()
t_ground.goto(-30,22)
t_ground.pendown()
t_ground.circle(25)
t_ground.end_fill()

t_ground.fillcolor('light gray')
t_ground.begin_fill()
t_ground.penup()
t_ground.goto(-30,-20)
t_ground.pendown()
t_ground.circle(30)
t_ground.end_fill()

t_ground.fillcolor('black')
t_ground.begin_fill()
t_ground.penup()
t_ground.goto(-30,58)
t_ground.pendown()
t_ground.circle(5)
t_ground.end_fill()

t_ground.fillcolor('black')
t_ground.begin_fill()
t_ground.penup()
t_ground.goto(-30,45)
t_ground.pendown()
t_ground.circle(5)
t_ground.end_fill()

t_ground.fillcolor('black')
t_ground.begin_fill()
t_ground.penup()
t_ground.goto(-30,24)
t_ground.pendown()
t_ground.circle(5)
t_ground.end_fill()

t_ground.fillcolor('black')
t_ground.begin_fill()
t_ground.penup()
t_ground.goto(-30,11)
t_ground.pendown()
t_ground.circle(5)
t_ground.end_fill()

t_ground.fillcolor('black')
t_ground.begin_fill()
t_ground.penup()
t_ground.goto(-30,-2)
t_ground.pendown()
t_ground.circle(5)
t_ground.end_fill()

t=turtle.Turtle()
t.hideturtle()

#First tree

t.penup()
t.goto(90,80)
t.pendown()
t.pensize(15)
t.pencolor("brown")
t.goto(90,5)

t.penup()
t.pensize(1)
t.pencolor('black')
t.fillcolor('snow2')
t.goto(20,40)
t.pendown()
t.begin_fill()
t.goto(90,210)
t.goto(160,40)
t.goto(20,40)
t.end_fill()

#Second tree

t.penup()
t.goto(200,50)
t.pendown()
t.pensize(15)
t.pencolor("brown")
t.goto(200,0)

t.penup()
t.pensize(1)
t.pencolor('black')
t.fillcolor('snow2')
t.goto(130,30)
t.pendown()
t.begin_fill()
t.goto(200,200)
t.goto(270,30)
t.goto(130,30)
t.end_fill()

#Third tree

t.penup()
t.goto(-200,50)
t.pendown()
t.pensize(15)
t.pencolor("brown")
t.goto(-200,0)

t.penup()
t.pensize(1)
t.pencolor('black')
t.fillcolor('snow2')
t.goto(-130,30)
t.pendown()
t.begin_fill()
t.goto(-200,200)
t.goto(-270,30)
t.goto(-130,30)
t.end_fill()

#Gift box
t.penup()
t.goto(-50,-20)
t.pendown()
t.pencolor('black')
t.fillcolor('red')
t.begin_fill()
t.goto(-15,10)
t.goto(-15,-20)
t.goto(-50,-20)
t.end_fill()

#Message
t.penup()
t.goto(0,75)
t.write("We got you a present! It's a acute triangle! The pythagorean theorem is engraved on it! 100 is the only acceptable grade, remember",font=("Aerial",24,"Bold"),align="center")
#this is the last line
turtle.done()
